### ISSUE TITLE
Crash implicating your UI

### ISSUE THREAD

**Issue by MentalMouse** [Corail31/recycler#1]
I was trying to recycle some gold boots that I'd just repaired with EvilCraft's Blood Chest.

http://pastebin.com/DKCzVqvZ

**Comment by MentalMouse** [comment]
Addendum:  Since getting that crash, I can't even open the recycler GUI:  The right-click has no effect, and this shows up in the log:

[09:57:13] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) [byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at ovh.corail.recycler.core.RecyclingManager.getResultStack(RecyclingManager.java:90) ~[RecyclingManager.class:?]
	at ovh.corail.recycler.core.RecyclingManager.getResultStack(RecyclingManager.java:75) ~[RecyclingManager.class:?]
	at ovh.corail.recycler.tileentity.TileEntityRecycler.refreshVisual(TileEntityRecycler.java:312) ~[TileEntityRecycler.class:?]
	at ovh.corail.recycler.container.ContainerRecycler.<init>(ContainerRecycler.java:40) ~[ContainerRecycler.class:?]
	at ovh.corail.recycler.handler.GuiHandler.getServerGuiElement(GuiHandler.java:25) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:244) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:80) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462) ~[zj.class:?]
	at ovh.corail.recycler.block.BlockRecycler.func_180639_a(BlockRecycler.java:50) ~[BlockRecycler.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:447) ~[ls.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:680) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:55) ~[jg.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:11) ~[jg.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more
[09:57:13] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) [byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at ovh.corail.recycler.core.RecyclingManager.getResultStack(RecyclingManager.java:90) ~[RecyclingManager.class:?]
	at ovh.corail.recycler.core.RecyclingManager.getResultStack(RecyclingManager.java:75) ~[RecyclingManager.class:?]
	at ovh.corail.recycler.tileentity.TileEntityRecycler.refreshVisual(TileEntityRecycler.java:312) ~[TileEntityRecycler.class:?]
	at ovh.corail.recycler.packet.VisualMessage$1.run(VisualMessage.java:30) ~[VisualMessage$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more

**Comment by Corail31** [comment]
Can you break the recycler and try it again plz?
I don't know this mod blood chest, and there's no reason in the code to make a crash.
The only thing that can make trouble is the nugget when a damaged item is recycled.

**Comment by Corail31** [comment]
is it version 1.1.3? i contacted the modeler of evilcraft to see his opinion.

**Comment by MentalMouse** [comment]
Breaking the recycler gets the original item back and the recycler, and sometimes gets back functionality.  However, I've got a couple of gold helmets that consistently crash, and a gold boots that have also crashed.  All these items came from my EvilCraft salvage of mob armor, that is Purifier to strip the enchantments, Blood Chest to repair them.  I can only guess that this process has left tags behind (perhaps from the former enchantments?   Repair penalty?) that your recycler is choking on.

**Comment by Corail31** [comment]
it crashed on a simply request on the item ;) stack.getItemDamage() > 0 (that allows the recycler to know it has to transform raw material in nugget before recycling)

**Comment by Corail31** [comment]
The bug is only a wrong recipe id... so, if you want to correct it faster than waiting for the release, you can edit recyclingRecipes.json in your config folder : look for minecraft:golden_ingot and replace them with minecraft:gold_ingot.
Sorry for this :)

**Comment by MentalMouse** [comment]
Thanks!
